global:
  imagePullSecrets:
    - name: regcred
replicas: 1
headlessService: true
useStatefulSet: true
# service:
  # type: NodePort
# ingress:
  # enabled: true
  # ingressClassName: cce
  # hosts:
    # - <HOSTNAME> 
  # tls:
  ##- secretName: my-tls
  ##     hosts: my-host
  # annotations:
    # kubernetes.io/elb.port: '80'
    # kubernetes.io/elb.class: union
    # kubernetes.io/ingress.class: cce
    # kubernetes.io/elb.autocreate: '{"type":"public","bandwidth_name":"cce-grafana","bandwidth_chargemode":"traffic","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_mailbgp"}'
persistence:
  type: pvc
  enabled: true 
  storageClassName: csi-disk-topology 
  accessModes:
    - ReadWriteOnce
  size: 10Gi
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki:3100 
      orgId: 1
    - name: Prometheus
      type: prometheus
      url: http://prometheus-community-server
